structures/urls.py
"""Tasks for Structures."""

from django.urls import path

from . import views

app_name = "structures"

urlpatterns = [
    path("", views.index, name="index"),
    path("list", views.main, name="main"),
    path("list_data", views.structure_list_data, name="structure_list_data"),
    path("summary_data", views.structure_summary_data, name="structure_summary_data"),
    path("add_structure_owner", views.add_structure_owner, name="add_structure_owner"),
    path("poco_list_data", views.poco_list_data, name="poco_list_data"),
    path(
        "jump_gates_list_data", views.jump_gates_list_data, name="jump_gates_list_data"
    ),
    path("service_status", views.service_status, name="service_status"),
    path(
        "<int:structure_id>/structure_details",
        views.structure_details,
        name="structure_details",
    ),
    path(
        "<int:structure_id>/poco_details",
        views.poco_details,
        name="poco_details",
    ),
    path(
        "<int:structure_id>/starbase_detail",
        views.starbase_detail,
        name="starbase_detail",
    ),
]

structures/models/structures_2.py
"""Models related to Structure."""

import datetime as dt
from typing import Optional

from django.db import models
from django.utils.translation import gettext_lazy as _
from eveuniverse.models import EveType

from allianceauth.eveonline.models import EveCharacter
from allianceauth.services.hooks import get_extension_logger
from app_utils.logging import LoggerAddTag

from structures import __title__
from structures.constants import EveGroupId
from structures.core import starbases

from .structures_1 import Structure

logger = LoggerAddTag(get_extension_logger(__name__), __title__)


class StructureService(models.Model):
    """Service of a Structure."""

    class State(models.IntegerChoices):
        """A state of a structure service."""

        OFFLINE = 1, _("offline")
        ONLINE = 2, _("online")

        @classmethod
        def from_esi_name(cls, esi_state_name: str) -> "StructureService.State":
            """Return matching state for given ESI state name."""
            states_esi_map = {"offline": cls.OFFLINE, "online": cls.ONLINE}
            return (
                states_esi_map[esi_state_name]
                if esi_state_name in states_esi_map
                else cls.OFFLINE
            )

    structure = models.ForeignKey(
        Structure,
        on_delete=models.CASCADE,
        related_name="services",
        verbose_name=_("structure"),
        help_text=_("Structure this service is installed to"),
    )
    name = models.CharField(
        max_length=100, verbose_name=_("name"), help_text=_("Name of the service")
    )

    state = models.IntegerField(
        choices=State.choices,
        verbose_name=_("state"),
        help_text=_("Current state of this service"),
    )

    class Meta:
        verbose_name = _("structure service")
        verbose_name_plural = _("structure services")
        unique_together = (("structure", "name"),)

    def __str__(self):
        return f"{self.structure} - {self.name}"

    def __repr__(self):
        return (
            f"{self.__class__.__name__}("
            f"structure_id={self.structure.id}, name='{self.name}')"
        )


class PocoDetails(models.Model):
    """Additional information about a POCO."""

    class StandingLevel(models.IntegerChoices):
        """A standing level in Eve Online."""

        NONE = -99, _("none")
        TERRIBLE = -10, _("terrible")
        BAD = -5, _("bad")
        NEUTRAL = 0, _("neutral")
        GOOD = 5, _("good")
        EXCELLENT = 10, _("excellent")

        @classmethod
        def from_esi(cls, value) -> "PocoDetails.StandingLevel":
            """Return match from ESI value or NONE"""
            my_map = {
                "bad": cls.BAD,
                "excellent": cls.EXCELLENT,
                "good": cls.GOOD,
                "neutral": cls.NEUTRAL,
                "terrible": cls.TERRIBLE,
            }
            try:
                return my_map[value]
            except KeyError:
                return cls.NONE

    alliance_tax_rate = models.FloatField(null=True, default=None)
    allow_access_with_standings = models.BooleanField()
    allow_alliance_access = models.BooleanField()
    bad_standing_tax_rate = models.FloatField(null=True, default=None)
    corporation_tax_rate = models.FloatField(null=True, default=None)
    excellent_standing_tax_rate = models.FloatField(null=True, default=None)
    good_standing_tax_rate = models.FloatField(null=True, default=None)
    neutral_standing_tax_rate = models.FloatField(null=True, default=None)
    reinforce_exit_end = models.PositiveIntegerField()
    reinforce_exit_start = models.PositiveIntegerField()
    standing_level = models.IntegerField(
        choices=StandingLevel.choices, default=StandingLevel.NONE
    )
    structure = models.OneToOneField(
        Structure, on_delete=models.CASCADE, related_name="poco_details"
    )
    terrible_standing_tax_rate = models.FloatField(null=True, default=None)

    def __str__(self):
        return f"{self.structure}"

    @property
    def reinforce_exit_end_str(self) -> str:
        """Return reinforce exit end as string."""
        return f"{self.reinforce_exit_end}:00"

    @property
    def reinforce_exit_start_str(self) -> str:
        """Return reinforce exit start as string."""
        return f"{self.reinforce_exit_start}:00"

    def tax_for_character(self, character: EveCharacter) -> Optional[float]:
        """Return the effective tax for this character or None if unknown."""
        owner_corporation = self.structure.owner.corporation
        if character.corporation_id == owner_corporation.corporation_id:
            return self.corporation_tax_rate

        if (
            owner_corporation.alliance
            and owner_corporation.alliance.alliance_id == character.alliance_id
        ):
            return self.alliance_tax_rate

        return None

    def has_character_access(self, character: EveCharacter) -> Optional[bool]:
        """Return Tru if this has access else False."""
        owner_corporation = self.structure.owner.corporation
        if character.corporation_id == owner_corporation.corporation_id:
            return True

        if (
            owner_corporation.alliance
            and owner_corporation.alliance.alliance_id == character.alliance_id
        ):
            return self.allow_alliance_access

        return None

    def standing_level_access_map(self) -> dict:
        """Return map of access per standing level with standing level names as key."""
        names_map = {
            self.StandingLevel.NONE: "NONE",
            self.StandingLevel.TERRIBLE: "TERRIBLE",
            self.StandingLevel.BAD: "BAD",
            self.StandingLevel.NEUTRAL: "NEUTRAL",
            self.StandingLevel.GOOD: "GOOD",
            self.StandingLevel.EXCELLENT: "EXCELLENT",
        }
        return {
            names_map[self.StandingLevel(level)]: (
                self.allow_access_with_standings and level >= self.standing_level
            )
            for level in self.StandingLevel.values
        }


class StarbaseDetail(models.Model):
    """Additional information about a starbase."""

    class Role(models.TextChoices):
        """A role for a starbase."""

        ALLIANCE_MEMBER = "AL", _("alliance member")
        CONFIG_STARBASE_EQUIPMENT_ROLE = "CE", _("config starbase equipment role")
        CORPORATION_MEMBER = "CO", _("corporation member")
        STARBASE_FUEL_TECHNICIAN_ROLE = "FT", _("starbase fuel technician role")

        @classmethod
        def from_esi(cls, name: str) -> "StarbaseDetail.Role":
            """Create role from ESI name."""
            my_map = {
                "alliance_member": cls.ALLIANCE_MEMBER,
                "config_starbase_equipment_role": cls.CONFIG_STARBASE_EQUIPMENT_ROLE,
                "corporation_member": cls.CORPORATION_MEMBER,
                "starbase_fuel_technician_role": cls.STARBASE_FUEL_TECHNICIAN_ROLE,
            }
            return my_map[name]

    allow_alliance_members = models.BooleanField()
    allow_corporation_members = models.BooleanField()
    anchor_role = models.CharField(max_length=2, choices=Role.choices)
    attack_if_at_war = models.BooleanField()
    attack_if_other_security_status_dropping = models.BooleanField()
    attack_security_status_threshold = models.FloatField(default=None, null=True)
    attack_standing_threshold = models.FloatField(default=None, null=True)
    fuel_bay_take_role = models.CharField(max_length=2, choices=Role.choices)
    fuel_bay_view_role = models.CharField(max_length=2, choices=Role.choices)
    last_modified_at = models.DateTimeField(
        help_text="When data was modified on the server."
    )
    offline_role = models.CharField(max_length=2, choices=Role.choices)
    online_role = models.CharField(max_length=2, choices=Role.choices)
    structure = models.OneToOneField(
        Structure, on_delete=models.CASCADE, related_name="starbase_detail"
    )
    unanchor_role = models.CharField(max_length=2, choices=Role.choices)
    use_alliance_standings = models.BooleanField()

    def __str__(self) -> str:
        return str(self.structure)

    def calc_fuel_expires(self) -> Optional[dt.datetime]:
        """Estimate when fuel will expire for this starbase.

        Estimate will vary due to server caching of remaining fuel blocks.
        """
        if self.structure.state is Structure.State.POS_OFFLINE:
            return None
        fuel = self.fuels.filter(eve_type__eve_group_id=EveGroupId.FUEL_BLOCK).first()
        if not fuel:
            return None
        seconds = starbases.fuel_duration(
            starbase_type=self.structure.eve_type,
            fuel_quantity=fuel.quantity,
            has_sov=self.structure.owner.has_sov(self.structure.eve_solar_system),
        )
        return self.last_modified_at + dt.timedelta(seconds=seconds)


class StarbaseDetailFuel(models.Model):
    """Fuel for a starbase detail."""

    eve_type = models.ForeignKey(EveType, on_delete=models.CASCADE, related_name="+")
    detail = models.ForeignKey(
        StarbaseDetail, on_delete=models.CASCADE, related_name="fuels"
    )
    quantity = models.IntegerField()

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["detail", "eve_type"], name="functional_pk_starbasedetailfuel"
            )
        ]

    def __str__(self) -> str:
        return f"{self.detail}-{self.eve_type}"

structures/templates/structures/modals/fitting_asset_items.html
{% load i18n %}

<li class="list-group-item list-group-item-custom">{% translate slot_name %}</li>
{% if asset_list|length == 0 %}
    <li class="list-group-item text-muted">{% translate "No Items" %}</li>
{% else %}
    {% for asset in asset_list %}
        {% include "structures/modals/fitting_asset.html" %}
    {% endfor %}
{% endif %}

structures/templates/structures/modals/fitting_assets.html
{% load i18n %}
{% load structures %}

{% list_title slot_name %}

{% for asset in asset_list %}
    {% list_asset asset.eve_type asset.quantity asset.is_singleton %}
{% empty %}
    <li class="list-group-item text-muted">{% translate "empty" %}</li>
{% endfor %}

structures/templates/structures/modals/fitting_gfx.html
{% load static %}
{% load evelinks %}

<div id="Fitting_Panel" style="position: relative; height:398px; width:398px; z-index: 3; margin: 0 auto;" >
    <div id="mask" style="position:absolute; left: 0px; top: 0px; width:398px; height:398px; z-index:-1;">
        <img style="position:absolute; left: 0px; top: 0px;  height:398px; width:398px; border:0px" src="{% static 'structures/img/panel/tyrannis.png' %}" alt="" />
    </div>

    <div id="highx" style="position:absolute; left: 0px; top: 0px; width: 398px; height: 398px; z-index:-1;">
        <img src="{{ slots.high }}" alt="" style="border:0px;" />
    </div>
    <div id="high1" style="position:absolute; left:73px; top:60px; width:32px; height:32px;">{% if assets_grouped.HiSlot0 %}<img src="{{ assets_grouped.HiSlot0.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.HiSlot0.eve_type.name }}">{% endif %}</div>
    <div id="high2" style="position:absolute; left:102px; top:42px; width:32px; height:32px;">{% if assets_grouped.HiSlot1 %}<img src="{{ assets_grouped.HiSlot1.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.HiSlot1.eve_type.name }}">{% endif %}</div>
    <div id="high3" style="position:absolute; left:134px; top:27px; width:32px; height:32px;">{% if assets_grouped.HiSlot2 %}<img src="{{ assets_grouped.HiSlot2.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.HiSlot2.eve_type.name }}">{% endif %}</div>
    <div id="high4" style="position:absolute; left:169px; top:21px; width:32px; height:32px;">{% if assets_grouped.HiSlot3 %}<img src="{{ assets_grouped.HiSlot3.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.HiSlot3.eve_type.name }}">{% endif %}</div>
    <div id="high5" style="position:absolute; left:203px; top:22px; width:32px; height:32px;">{% if assets_grouped.HiSlot4 %}<img src="{{ assets_grouped.HiSlot4.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.HiSlot4.eve_type.name }}">{% endif %}</div>
    <div id="high6" style="position:absolute; left:238px; top:30px; width:32px; height:32px;">{% if assets_grouped.HiSlot5 %}<img src="{{ assets_grouped.HiSlot5.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.HiSlot5.eve_type.name }}">{% endif %}</div>
    <div id="high7" style="position:absolute; left:270px; top:45px; width:32px; height:32px;">{% if assets_grouped.HiSlot6 %}<img src="{{ assets_grouped.HiSlot6.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.HiSlot6.eve_type.name }}">{% endif %}</div>
    <div id="high8" style="position:absolute; left:295px; top:64px; width:32px; height:32px;">{% if assets_grouped.HiSlot7 %}<img src="{{ assets_grouped.HiSlot7.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.HiSlot7.eve_type.name }}">{% endif %}</div>

    <div id="midx" style="position:absolute; left: 0px; top: 0px; width: 398px; height: 398px; z-index:-1;">
        <img src="{{ slots.med }}" alt="" style="border:0px;" />
    </div>
    <div id="mid1" style="position:absolute; left:26px; top:140px; width:32px; height:32px;">{% if assets_grouped.MedSlot0 %}<img src="{{ assets_grouped.MedSlot0.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.MedSlot0.eve_type.name }}">{% endif %}</div>
    <div id="mid2" style="position:absolute; left:24px; top:176px; width:32px; height:32px;">{% if assets_grouped.MedSlot1 %}<img src="{{ assets_grouped.MedSlot1.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.MedSlot1.eve_type.name }}">{% endif %}</div>
    <div id="mid3" style="position:absolute; left:23px; top:212px; width:32px; height:32px;">{% if assets_grouped.MedSlot2 %}<img src="{{ assets_grouped.MedSlot2.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.MedSlot2.eve_type.name }}">{% endif %}</div>
    <div id="mid4" style="position:absolute; left:30px; top:245px; width:32px; height:32px;">{% if assets_grouped.MedSlot3 %}<img src="{{ assets_grouped.MedSlot3.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.MedSlot3.eve_type.name }}">{% endif %}</div>
    <div id="mid5" style="position:absolute; left:46px; top:278px; width:32px; height:32px;">{% if assets_grouped.MedSlot4 %}<img src="{{ assets_grouped.MedSlot4.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.MedSlot4.eve_type.name }}">{% endif %}</div>
    <div id="mid6" style="position:absolute; left:69px; top:304px; width:32px; height:32px;">{% if assets_grouped.MedSlot5 %}<img src="{{ assets_grouped.MedSlot5.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.MedSlot5.eve_type.name }}">{% endif %}</div>
    <div id="mid7" style="position:absolute; left:100px; top:328px; width:32px; height:32px;">{% if assets_grouped.MedSlot6 %}<img src="{{ assets_grouped.MedSlot6.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.MedSlot6.eve_type.name }}">{% endif %}</div>
    <div id="mid8" style="position:absolute; left:133px; top:342px; width:32px; height:32px;">{% if assets_grouped.MedSlot7 %}<img src="{{ assets_grouped.MedSlot7.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.MedSlot7.eve_type.name }}">{% endif %}</div>

    <div id="lowx" style="position:absolute; left: 0px; top: 0px; width: 398px; height: 398px; z-index:-1;">
        <img src="{{ slots.low }}" alt="" style="border:0px;" />
    </div>
    <div id="low1" style="position:absolute; left:344px; top:143px; width:32px; height:32px;">{% if assets_grouped.LoSlot0 %}<img src="{{ assets_grouped.LoSlot0.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.LoSlot0.eve_type.name }}">{% endif %}</div>
    <div id="low2" style="position:absolute; left:350px; top:178px; width:32px; height:32px;">{% if assets_grouped.LoSlot1 %}<img src="{{ assets_grouped.LoSlot1.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.LoSlot1.eve_type.name }}">{% endif %}</div>
    <div id="low3" style="position:absolute; left:349px; top:213px; width:32px; height:32px;">{% if assets_grouped.LoSlot2 %}<img src="{{ assets_grouped.LoSlot2.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.LoSlot2.eve_type.name }}">{% endif %}</div>
    <div id="low4" style="position:absolute; left:340px; top:246px; width:32px; height:32px;">{% if assets_grouped.LoSlot3 %}<img src="{{ assets_grouped.LoSlot3.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.LoSlot3.eve_type.name }}">{% endif %}</div>
    <div id="low5" style="position:absolute; left:323px; top:277px; width:32px; height:32px;">{% if assets_grouped.LoSlot4 %}<img src="{{ assets_grouped.LoSlot4.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.LoSlot4.eve_type.name }}">{% endif %}</div>
    <div id="low6" style="position:absolute; left:300px; top:304px; width:32px; height:32px;">{% if assets_grouped.LoSlot5 %}<img src="{{ assets_grouped.LoSlot5.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.LoSlot5.eve_type.name }}">{% endif %}</div>
    <div id="low7" style="position:absolute; left:268px; top:324px; width:32px; height:32px;">{% if assets_grouped.LoSlot6 %}<img src="{{ assets_grouped.LoSlot6.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.LoSlot6.eve_type.name }}">{% endif %}</div>
    <div id="low8" style="position:absolute; left:234px; top:338px; width:32px; height:32px;">{% if assets_grouped.LoSlot7 %}<img src="{{ assets_grouped.LoSlot7.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.LoSlot7.eve_type.name }}">{% endif %}</div>

    <div id="rigxx" style="position:absolute; left: 0px; top: 0px; width: 398px; height: 398px; z-index:-1;">
        <img src="{{ slots.rig }}" alt="" style="border:0px;" />
    </div>
    <div id="rig1" style="position:absolute; left:148px; top:259px; width:32px; height:32px;">{% if assets_grouped.RigSlot0 %}<img src="{{ assets_grouped.RigSlot0.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.RigSlot0.eve_type.name }}">{% endif %}</div>
    <div id="rig2" style="position:absolute; left:185px; top:267px; width:32px; height:32px;">{% if assets_grouped.RigSlot1 %}<img src="{{ assets_grouped.RigSlot1.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.RigSlot1.eve_type.name }}">{% endif %}</div>
    <div id="rig3" style="position:absolute; left:221px; top:259px; width:32px; height:32px;">{% if assets_grouped.RigSlot2 %}<img src="{{ assets_grouped.RigSlot2.eve_type_id|type_icon_url:128 }}" style="height: 32px; width: 32px;" title="{{ assets_grouped.RigSlot2.eve_type.name }}">{% endif %}</div>
    <div id="bigship" style='position:absolute; left:72px; top:71px; width:256px; height:256px; z-index:-2;'>
        <img class="img-rounded" src="{{ structure.eve_type_id|type_render_url:256 }}" style="height: 256px; width: 256px;">
    </div>
</div>

structures/templates/structures/modals/starbase_detail.html
{% load i18n %}
{% load static %}
{% load humanize %}
{% load structures %}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title">{{structure}}</h4>
</div>

<div class="modal-body">
    {% detail_title structure %}
    <br>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
            <a href="#tab-starbase-general" aria-controls="modules" role="tab" data-toggle="tab">
                {% translate "General" %}
            </a>
        </li>
        <li role="presentation">
            <a href="#tab-starbase-fuel" aria-controls="fuels" role="tab" data-toggle="tab">
                {% translate "Fuel" %} <small>({{ fuel_blocks_count|default:"-"|intcomma }})</small>
            </a>
        </li>
        <li role="presentation">
            <a href="#tab-starbase-modules" aria-controls="modules" role="tab" data-toggle="tab">
                {% translate "Modules" %} <small>({{ modules_count }})</small>
            </a>
        </li>
        <li role="presentation">
            <a href="#tab-starbase-settings" aria-controls="settings" role="tab" data-toggle="tab">
                {% translate "Settings" %}
            </a>
        </li>
        <li role="presentation">
            <a href="#tab-starbase-access" aria-controls="access" role="tab" data-toggle="tab">
                {% translate "Access" %}
            </a>
        </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="tab-starbase-general">
            {% include "structures/modals/tab_general_detail.html" %}
        </div>

        <div role="tabpanel" class="tab-pane" id="tab-starbase-fuel">
            <ul class="list-group">
                {% for fuel in fuels %}
                    {% list_asset fuel.eve_type fuel.quantity %}
                {% empty %}
                    {% list_item _("empty") is_muted=True %}
                {% endfor %}
            </ul>
        </div>

        <div role="tabpanel" class="tab-pane" id="tab-starbase-modules">
            <ul class="list-group">
                {% for item in modules %}
                    {% list_asset item.eve_type item.quantity %}
                {% empty %}
                    {% list_item _("empty") is_muted=True %}
                {% endfor %}
            </ul>
        </div>

        <div role="tabpanel" class="tab-pane" id="tab-starbase-settings">
            <ul class="list-group">
                {% list_item _("Allow alliance member usage") detail.allow_alliance_members %}
                {% list_item _("Allow corporation member usage") detail.allow_corporation_members %}
                {% list_item _("Attack if standing lower than") detail.attack_standing_threshold %}
                {% list_item _("Attack if security status lower than") detail.attack_security_status_threshold %}
                {% list_item _("Attack if other security status is dropping") detail.attack_if_other_security_status_dropping %}
                {% list_item _("Attack if at war") detail.attack_if_at_war %}
                {% list_item _("Use alliance standings") detail.use_alliance_standings %}
            </ul>
        </div>

        <div role="tabpanel" class="tab-pane" id="tab-starbase-access">
            <ul class="list-group">
                {% list_item _("Anchor role") detail.get_anchor_role_display %}
                {% list_item _("Unanchor role") detail.get_unanchor_role_display %}
                {% list_item _("Online role") detail.get_online_role_display %}
                {% list_item _("Offline role") detail.get_offline_role_display %}
                {% list_item _("Fuel bay view role") detail.get_fuel_bay_view_role_display %}
                {% list_item _("Fuel bay take role") detail.get_fuel_bay_take_role_display %}
            </ul>
        </div>
    </div>

    <br>
    <p class="text-muted">Last updated {{ last_updated_at|naturaltime|default:"?" }}</p>
</div>

structures/templates/structures/modals/tab_general_detail.html
{% load i18n %}
{% load evelinks %}
{% load structures %}

<ul class="list-group">
    {% list_item _("Name") structure.name|default:"-" %}
    {% list_item _("Type") structure.eve_type.name url=structure.eve_type.profile_url %}
    {% list_item _("Corporation") structure.owner url=structure.owner.corporation|dotlan_corporation_url %}
    {% with alliance=structure.owner.corporation.alliance %}
        {% list_item _("Alliance") alliance|default:"-" url=alliance|dotlan_alliance_url %}
    {% endwith %}
    {% list_item _("Location") structure.location_name url=structure.eve_solar_system.profile_url %}
    {% list_item _("Constellation") structure.eve_solar_system.eve_constellation %}
    {% with eve_region=structure.eve_solar_system.eve_constellation.eve_region %}
        {% list_item _("Region") eve_region.name url=eve_region|dotlan_region_url %}
    {% endwith %}
    {% if not structure.is_poco %}
        {% list_item _("State") structure.get_state_display %}
    {% endif %}
</ul>