structures/urls.py
"""Tasks for Structures."""

from django.urls import path

from . import views

app_name = "structures"

urlpatterns = [
    path("", views.index, name="index"),
    path("list", views.main, name="main"),
    path("list_data", views.structure_list_data, name="structure_list_data"),
    path("summary_data", views.structure_summary_data, name="structure_summary_data"),
    path("add_structure_owner", views.add_structure_owner, name="add_structure_owner"),
    path("poco_list_data", views.poco_list_data, name="poco_list_data"),
    path(
        "jump_gates_list_data", views.jump_gates_list_data, name="jump_gates_list_data"
    ),
    path("service_status", views.service_status, name="service_status"),
    path(
        "<int:structure_id>/structure_details",
        views.structure_details,
        name="structure_details",
    ),
    path(
        "<int:structure_id>/poco_details",
        views.poco_details,
        name="poco_details",
    ),
    path(
        "<int:structure_id>/starbase_detail",
        views.starbase_detail,
        name="starbase_detail",
    ),
]

structures/models/structures.py
"""Structure related models for Structures."""

import datetime as dt
import math
import re
from typing import List, Optional

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models, transaction
from django.db.models import Min, Sum
from django.utils.functional import cached_property
from django.utils.html import escape
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from django.utils.translation import gettext_noop
from eveuniverse.models import EveMoon, EvePlanet, EveSolarSystem, EveType

from allianceauth.eveonline.models import EveCharacter
from allianceauth.services.hooks import get_extension_logger
from app_utils.logging import LoggerAddTag
from app_utils.views import bootstrap_label_html

from .. import __title__
from ..app_settings import STRUCTURES_FEATURE_REFUELED_NOTIFICATIONS
from ..constants import EveCategoryId, EveGroupId, EveTypeId
from ..core import starbases
from ..helpers.general import datetime_almost_equal, hours_until_deadline
from ..managers import StructureManager, StructureTagManager
from .eveuniverse import EveSpaceType

logger = LoggerAddTag(get_extension_logger(__name__), __title__)


class StructureTag(models.Model):
    """Tag for organizing structures."""

    # special tags
    NAME_SOV_TAG = gettext_noop("sov")
    NAME_HIGHSEC_TAG = gettext_noop("highsec")
    NAME_LOWSEC_TAG = gettext_noop("lowsec")
    NAME_NULLSEC_TAG = gettext_noop("nullsec")
    NAME_W_SPACE_TAG = gettext_noop("w_space")

    class Style(models.TextChoices):
        """A boostrap like style."""

        GREY = "default", _("grey")
        DARK_BLUE = "primary", _("dark blue")
        GREEN = "success", _("green")
        LIGHT_BLUE = "info", _("light blue")
        ORANGE = "warning", _("orange")
        RED = "danger", _("red")

    SPACE_TYPE_MAP = {
        EveSpaceType.HIGHSEC: {"name": NAME_HIGHSEC_TAG, "style": Style.GREEN},
        EveSpaceType.LOWSEC: {"name": NAME_LOWSEC_TAG, "style": Style.ORANGE},
        EveSpaceType.NULLSEC: {"name": NAME_NULLSEC_TAG, "style": Style.RED},
        EveSpaceType.W_SPACE: {"name": NAME_W_SPACE_TAG, "style": Style.LIGHT_BLUE},
    }

    name = models.CharField(
        max_length=255,
        unique=True,
        verbose_name=_("name"),
        help_text=_("name of the tag - must be unique"),
    )
    description = models.TextField(
        null=True,
        default=None,
        blank=True,
        verbose_name=_("description"),
        help_text=_("description for this tag"),
    )
    style = models.CharField(
        max_length=16,
        choices=Style.choices,
        default="default",
        blank=True,
        verbose_name=_("style"),
        help_text=_("color style of tag"),
    )
    order = models.PositiveIntegerField(
        default=100,
        blank=True,
        validators=[MinValueValidator(100)],
        verbose_name=_("order"),
        help_text=_(
            "number defining the order tags are shown. "
            "custom tags can not have an order below 100"
        ),
    )
    is_default = models.BooleanField(
        default=False,
        verbose_name=_("is default"),
        help_text=_(
            "if true this custom tag will automatically be added to new structures"
        ),
    )
    is_user_managed = models.BooleanField(
        default=True,
        verbose_name=_("is user managed"),
        help_text=_(
            "if False this tag is created and managed by the system "
            "and can not be modified by users"
        ),
    )

    objects = StructureTagManager()

    class Meta:
        verbose_name = _("structure tag")
        verbose_name_plural = _("structure tags")
        ordering = ["order", "name"]

    def __str__(self) -> str:
        return self.name

    def __repr__(self):
        return f"{self.__class__.__name__}(name='{self.name}')"

    @property
    def html(self) -> str:
        """Return HTML for this tag."""
        if self.is_user_managed:
            name = escape(self.name)
        else:
            name = _(self.name)
        return bootstrap_label_html(name, self.style)

    @classmethod
    def sorted(cls, tags: list, reverse: bool = False) -> list:
        """returns a sorted copy of the provided list of tags"""
        return sorted(tags, key=lambda x: x.name.lower(), reverse=reverse)


class Structure(models.Model):  # pylint: disable = too-many-public-methods
    """A structure in Eve Online."""

    FUEL_DATES_EQUAL_THRESHOLD_UPWELL = 1800
    """Threshold in seconds when two fuel expiry dates will be judged as different."""

    FUEL_DATES_EQUAL_THRESHOLD_STARBASE = 7200
    """high fluctuation due to estimating."""

    class State(models.IntegerChoices):
        """A state of a structure."""

        # states Upwell structures
        ANCHOR_VULNERABLE = 1, _("anchor vulnerable")
        ANCHORING = 2, _("anchoring")
        ARMOR_REINFORCE = 3, _("armor reinforce")
        ARMOR_VULNERABLE = 4, _("armor vulnerable")
        DEPLOY_VULNERABLE = 5, _("deploy vulnerable")
        FITTING_INVULNERABLE = 6, _("fitting invulnerable")
        HULL_REINFORCE = 7, _("hull reinforce")
        HULL_VULNERABLE = 8, _("hull vulnerable")
        ONLINE_DEPRECATED = 9, _("online deprecated")
        ONLINING_VULNERABLE = 10, _("onlining vulnerable")
        SHIELD_VULNERABLE = 11, _("shield vulnerable")
        UNANCHORED = 12, _("unanchored")
        # starbases
        POS_OFFLINE = 21, _("offline")
        POS_ONLINE = 22, _("online")
        POS_ONLINING = 23, _("onlining")
        POS_REINFORCED = 24, _("reinforced")
        POS_UNANCHORING = 25, _("unanchoring ")
        # other
        NA = 0, _("N/A")
        UNKNOWN = 13, _("unknown")

        @classmethod
        def from_esi_name(cls, esi_state_name: str) -> "Structure.State":
            """returns matching state for esi state name of Upwell structures"""
            states_esi_map = {
                "anchor_vulnerable": cls.ANCHOR_VULNERABLE,
                "anchoring": cls.ANCHORING,
                "armor_reinforce": cls.ARMOR_REINFORCE,
                "armor_vulnerable": cls.ARMOR_VULNERABLE,
                "deploy_vulnerable": cls.DEPLOY_VULNERABLE,
                "fitting_invulnerable": cls.FITTING_INVULNERABLE,
                "hull_reinforce": cls.HULL_REINFORCE,
                "hull_vulnerable": cls.HULL_VULNERABLE,
                "online_deprecated": cls.ONLINE_DEPRECATED,
                "onlining_vulnerable": cls.ONLINING_VULNERABLE,
                "shield_vulnerable": cls.SHIELD_VULNERABLE,
                "unanchored": cls.UNANCHORED,
                "offline": cls.POS_OFFLINE,
                "online": cls.POS_ONLINE,
                "onlining": cls.POS_ONLINING,
                "reinforced": cls.POS_REINFORCED,
                "unanchoring ": cls.POS_UNANCHORING,
            }
            return (
                states_esi_map[esi_state_name]
                if esi_state_name in states_esi_map
                else cls.UNKNOWN
            )

    class PowerMode(models.TextChoices):
        """A power mode of a structure."""

        FULL_POWER = "FU", _("Full Power")
        LOW_POWER = "LO", _("Low Power")
        ABANDONED = "AB", _("Abandoned")
        LOW_ABANDONED = "LA", _("Abandoned?")
        UNKNOWN = "UN", _("Unknown")

    id = models.BigIntegerField(
        primary_key=True,
        verbose_name=_("id"),
        help_text=_("The Item ID of the structure"),
    )

    created_at = models.DateTimeField(
        default=now,
        verbose_name=_("created at"),
        help_text=_("date this structure was received from ESI for the first time"),
    )
    eve_moon = models.ForeignKey(
        EveMoon,
        on_delete=models.SET_DEFAULT,
        null=True,
        default=None,
        blank=True,
        related_name="+",
        verbose_name=_("moon"),
        help_text=_("Moon next to this structure - if any"),
    )
    eve_planet = models.ForeignKey(
        EvePlanet,
        on_delete=models.SET_DEFAULT,
        null=True,
        default=None,
        blank=True,
        related_name="+",
        verbose_name=_("planet"),
        help_text=_("Planet next to this structure - if any"),
    )
    eve_solar_system = models.ForeignKey(
        EveSolarSystem,
        on_delete=models.CASCADE,
        related_name="+",
        verbose_name=_("solar system"),
        help_text=_("Solar System the structure is located"),
    )
    eve_type = models.ForeignKey(
        EveType,
        on_delete=models.CASCADE,
        related_name="+",
        verbose_name=_("type"),
        help_text=_("Type of the structure"),
    )
    fuel_expires_at = models.DateTimeField(
        null=True,
        default=None,
        blank=True,
        verbose_name=_("fuel expires at"),
        help_text=_("Date on which the structure will run out of fuel"),
    )
    has_fitting = models.BooleanField(
        null=True,
        default=None,
        blank=True,
        db_index=True,
        verbose_name=_("has fitting"),
        help_text=_("bool indicating if the structure has a fitting"),
    )
    has_core = models.BooleanField(
        null=True,
        default=None,
        blank=True,
        db_index=True,
        verbose_name=_("has core"),
        help_text=_("bool indicating if the structure has a quantum core"),
    )
    last_online_at = models.DateTimeField(
        null=True,
        default=None,
        blank=True,
        verbose_name=_("last online at"),
        help_text=_("date this structure had any of it's services online"),
    )
    last_updated_at = models.DateTimeField(
        null=True,
        default=None,
        blank=True,
        verbose_name=_("last updated at"),
        help_text=_("date this structure was last updated from the EVE server"),
    )
    name = models.CharField(
        max_length=255,
        verbose_name=_("name"),
        help_text=_("The full name of the structure"),
    )

structures/templates/structures/partials/jump_gates_list.html
{% load i18n %}
{% load bootstrap %}
{% load static %}

<!-- structure list -->
<div role="tabpanel" class="tab-pane" id="jump-gates">
    <div class="table-responsive">
        <table id="tab_jump_gates" style="width: 100%" class="table table-striped table-compact">
            <thead>
                <tr>
                    <th></th>
                    <th>{% translate "Owner" %}</th>
                    <th>{% translate "Location" %}</th>
                    <th>{% translate "Name" %}</th>
                    <th>{% translate "Last Online" %}</th>
                    <th>{% translate "Fuel Expires" %}</th>
                    <th>{% translate "Liquid Ozone (units)" %}</th>
                </tr>
            </thead>
        </table>
        <p class="text-muted">
            {% translate "Reinforced structures (except POCOs) are highlighted in red" %}
        </p>
    </div>
</div>

<!-- Modals -->
<div class="modal" id="modalUpwellDetails" tabindex="-1" role="dialog" aria-labelledby="{% translate 'modalUpwellDetails '%}">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="modalUpwellDetailsContent">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Loading...</h4>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

structures/templates/structures/partials/poco_list.html
{% load i18n %}
{% load bootstrap %}

<div role="tabpanel" class="tab-pane" id="pocos">
    <div class="table-responsive">
        <table id="tab_pocos" style="width: 100%" class="table table-striped table-compact">
            <thead>
                <tr>
                    <th></th>
                    <th>{% translate "Region" %}</th>
                    <th>{% translate "Solar System" %}</th>
                    <th>{% translate "Planet" %}</th>
                    <th></th>
                    <th>{% translate "Planet Type" %}</th>
                    <th class="text-tooltip" title="For your main character {{ request.user.profile.main_character|default:'?' }}">
                        {% translate "Access?" %}
                    </th>
                    <th class="text-tooltip" title="For your main character {{ request.user.profile.main_character|default:'?' }}">
                        {% translate "Tax" %}
                    </th>
                </tr>
            </thead>
        </table>
    </div>
</div>

structures/templates/structures/partials/structure_list.html
{% load i18n %}
{% load bootstrap %}
{% load static %}

<!-- structure list -->
<div role="tabpanel" class="tab-pane" id="structures">
    <div class="table-responsive">
        <!-- Tags Filter Button -->
        <span class="pull-right">
            {% if tags_exist %}
                {% if active_tags %}
                    <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#modalTagsFilter">
                    {% translate "Tags Filter (Active)" %}
                    </button>
                {% else %}
                    <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modalTagsFilter">
                        {% translate "Tags Filter" %}
                    </button>
                {% endif %}
            {% else %}
                <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modalTagsFilter" disabled="disabled">
                    {% translate "Tags Filter" %}
                </button>
            {% endif %}
        </span>

        <!-- Tags Filter Modal -->
        <div class="modal" id="modalTagsFilter" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <form method="post">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <h4 class="modal-title">{% translate "Tags Filter" %}</h4>
                        </div>
                        <div class="modal-body">
                            {% csrf_token %}
                            {{ tags_filter_form|bootstrap }}
                        </div>
                        <div class="modal-footer">
                            <a class="btn btn-default pull-left" href="{% url 'structures:index' %}" role="button">
                                {% translate "Reset Filter" %}
                            </a>
                            <a class="btn btn-default pull-left" href="{% url 'structures:main' %}" role="button">
                                {% translate "Clear Filter" %}
                            </a>
                            <button type="button" class="btn btn-default" data-dismiss="modal">
                                {% translate "Cancel" %}
                            </button>
                            <button type="submit" class="btn btn-primary">
                                {% translate "Apply Filter" %}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <table id="tab_structures" style="width: 100%" class="table table-striped table-compact">
            <thead>
                <tr>
                    <th></th>
                    <th>{% translate "Owner" %}</th>
                    <th>{% translate "Location" %}</th>
                    <th></th>
                    <th>{% translate "Type" %}</th>
                    <th>{% translate "Name & Tags" %}</th>
                    <th>{% translate "Services" %}</th>
                    <th>{% translate "Last Online" %}</th>
                    <th>{% translate "Fuel Expires" %}</th>
                    <th>{% translate "R-Hour" %}</th>
                    <th>{% translate "State" %}</th>
                    <th>{% translate "Core" %}</th>
                    <th></th>
                </tr>
            </thead>
        </table>

        <p>
            {% if active_tags %}
                {% translate "Active Tags Filter" %}:&nbsp;
                {% for tag in active_tags %}
                    {{ tag.html }}&#32;
                {% endfor %}
            {% endif %}
        </p>
        <p class="text-muted">
            {% translate "Offlined services are shown as" %} <del>{% translate "service" %}</del>
            • {% translate "Reinforced structures (except POCOs) are highlighted in red" %}
        </p>
    </div>
</div>

<!-- Modals -->
<div class="modal" id="modalUpwellDetails" tabindex="-1" role="dialog" aria-labelledby="{% translate 'modalUpwellDetails '%}">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="modalUpwellDetailsContent">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Loading...</h4>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

<div class="modal" id="modalPocoDetails" tabindex="-1" role="dialog" aria-labelledby="modalPocoDetails">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="modalPocoDetailsContent">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Loading...</h4>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

<div class="modal" id="modalStarbaseDetail" tabindex="-1" role="dialog" aria-labelledby="modalStarbaseDetail">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="modalStarbaseDetailContent">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Loading...</h4>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

structures/templates/structures/partials/structure_summary.html
{% load i18n %}
{% load bootstrap %}

<div role="tabpanel" class="tab-pane" id="summary">
    <div class="table-responsive">
        <table id="tab_summary" style="width: 100%" class="table table-striped table-compact">
            <thead>
                <tr>
                    <th></th>
                    <th>{% translate "Corporation" %}</th>
                    <th>{% translate "Alliance" %}</th>
                    <th class="text-right">{% translate "Citadels" %}</th>
                    <th class="text-right">{% translate "Engineering Complexes" %}</th>
                    <th class="text-right">{% translate "Refineries" %}</th>
                    <th class="text-right">{% translate "Other Upwell" %}</th>
                    <th class="text-right">{% translate "Customs Offices" %}</th>
                    <th class="text-right">{% translate "Starbases" %}</th>
                    <th class="text-right">{% translate "Total" %}</th>
                </tr>
            </thead>
            <tfoot>
                <tr class="info">
                    <th></th>
                    <th>{% translate "Total" %}</th>
                    <th></th>
                    <th class="text-right"></th>
                    <th class="text-right"></th>
                    <th class="text-right"></th>
                    <th class="text-right"></th>
                    <th class="text-right"></th>
                    <th class="text-right"></th>
                    <th class="text-right"></th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>